api_platform:
    title: 'API Quality Metrics'
    description: 'API du projet Quality Metrics.'
    # Méthode d'incrément X.Y.Z
    # X : Evolutions majeures
    # Y : Evolutions
    # Z : Correctifs
    version: '0.0.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
